name: fitmemax
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  pinput: ^0.2.4
  ff_navigation_bar: ^0.1.4
  flutter_speed_dial: ^1.2.5
  page_transition: ^1.1.7+2
  liquid_swipe: ^1.5.0
  carousel_slider: ^2.3.1
  calendar_timeline: ^0.7.1
  image_picker: ^0.6.7+11
  fluttertoast: ^7.1.1
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^4.1.2
  flutter_staggered_grid_view: ^0.3.2
  cached_network_image: ^2.2.0+1
  video_player: ^1.0.1
  google_fonts: ^1.1.1
  sleek_circular_slider: ^1.2.0+web
  flutter_date_picker_timeline: ^0.1.3
  inview_notifier_list: ^1.0.0
  flutter_sparkline: ^0.1.0
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  sign_in_with_apple: ^2.5.4
  lottie: ^0.7.0+1
  flutter_staggered_animations: ^0.1.3
  delayed_display: ^1.1.0
  animator: ^2.0.2
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  adaptive_dialog: ^0.9.3
  flutter_html: ^1.1.1
  waveprogressbar_flutter: ^0.1.2
  flutter_svg: ^0.19.3
  fl_chart: ^0.35.0
  slider_button: ^0.6.0
  slide_digital_clock: ^1.0.0
  flip_card: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/background/
    - assets/logo/
    - assets/sign/
    - assets/dashboard/
    - assets/plans/
    - assets/dashboard/mainIcon/
    - assets/story/
    - assets/blog/
    - assets/profile/
    - assets/popup/
    - assets/icons/
    - assets/shop/
    - assets/coachs/
    - assets/plandetails/
    - assets/Coach/
    - assets/profile/Post/
    - assets/gif/
    - images/
    - assets/Badges/
    - assets/Rings/
    - assets/banner/
    - assets/gopro/
    - assets/others/
    - assets/calori/
    - assets/fast/
    - assets/battleground/
    - assets/workout/
    - assets/icon/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Ghost Clan
      fonts:
        - asset: fonts/ghostclan.ttf
    - family: Adora
      fonts:
        - asset: fonts/AdoraFresh.ttf