name: fitmemax
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_sign_in: ^5.0.4
  pinput: ^0.2.4
  flutter_speed_dial: ^1.2.5
  page_transition: ^1.1.7+2
  carousel_slider: ^2.3.1
  calendar_timeline: ^0.7.1
  image_picker: ^0.6.7+11
  fluttertoast: ^7.1.1
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^4.1.2
  cached_network_image: ^2.2.0+1
  google_fonts: ^1.1.1
  sleek_circular_slider: ^1.2.0+web
  flutter_date_picker_timeline: ^0.1.3
  inview_notifier_list: ^1.0.0
  flutter_sparkline: ^0.1.0
  sign_in_with_apple: ^2.5.4
  flutter_staggered_animations: ^0.1.3
  delayed_display: ^1.1.0
  animator: ^2.0.2
  http: ^0.12.2
  adaptive_dialog: ^0.9.3
  waveprogressbar_flutter: ^0.1.2
  fl_chart: ^0.35.0
  slider_button: ^0.6.0
  slide_digital_clock: ^1.0.0
  flip_card: ^0.5.0
  flutter_spinning_wheel: ^1.1.0
#  audioplayers: ^0.17.3
  flutter_svg: ^0.22.0
  dotted_border: ^2.0.0
  liquid_swipe: ^1.5.0
  ff_navigation_bar: ^0.1.5
  provider: ^4.0.2
  blinking_text: ^1.0.1+2
  shared_preferences: ^0.5.12+4
  video_player: ^2.2.5
  flutter_rating_bar: ^4.0.0
  flutter_login_facebook: ^1.4.1
  back_button_interceptor: ^5.0.2
  flutter_staggered_grid_view: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/background/
    - assets/logo/
    - assets/sign/
    - assets/dashboard/
    - assets/plans/
    - assets/dashboard/mainIcon/
    - assets/story/
    - assets/blog/
    - assets/profile/
    - assets/popup/
    - assets/icons/
    - assets/shop/
    - assets/coachs/
    - assets/plandetails/
    - assets/Coach/
    - assets/profile/Post/
    - assets/gif/
    - images/
    - images/gmap.jpg
    - assets/Badges/
    - assets/Rings/
    - assets/banner/
    - assets/gopro/
    - assets/others/
    - assets/calori/
    - assets/fast/
    - assets/battleground/
    - assets/workout/
    - assets/icon/
    - assets/battleground/audio/
    - assets/audio/
    - assets/yoga/
    - assets/meditation/
    - assets/eBook/
    - assets/battleground/beast/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Ghost Clan
      fonts:
        - asset: fonts/ghostclan.ttf
    - family: Adora
      fonts:
        - asset: fonts/AdoraFresh.ttf
